### ISSUE TITLE
event.js throwing unhandled error

### ISSUE THREAD

**Issue by jcalado** [sindresorhus/speed-test#38] opened 2016-07-19 09:09 UTC
➜  speedtests speed-test

Ping
Download
    Upload
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'settings' of null
    at gotServers (/usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:522:20)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:48:16
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:238:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:494:16)
    at Parser.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/speed-test/node_modules/xml2js/lib/xml2js.js:535:19)
    at /usr/local/lib/node_modules/speed-test/node_modules/speedtest-net/index.js:236:5
➜  speedtests

**Comment by SamVerschueren** [comment] 2016-07-19 09:16
duplicate of #36

**Closed by SamVerschueren** 2016-07-19 09:16 UTC
