### ISSUE TITLE
Consistently wrong speed 

### ISSUE THREAD

**Issue by sjmcdowall** [sindresorhus/speed-test#40] opened 2016-07-29 18:45 UTC
Every other speed test aligns with the theoretical speed I should be getting, namely 300Mb/s give or take ..  However, speed-test shows a consistent speed of 45 Mb/s:

 ✝  ~  speed-test --verbose

      Ping   67 ms
  Download   42 Mbps
    Upload   19 Mbps

    Server   speedtest1.citizens.coop
  Location   Floyd, VA (United States)
  Distance   94 km

Compare to "fast" (the old one I used to use) : 
 ✝  ~  fast

    300 Mbps

**Comment by sindresorhus** [comment] 2016-07-29 18:47
Duplicate of https://github.com/sindresorhus/speed-test/issues/11. Post your findings there ;)

**Closed by sindresorhus** 2016-07-29 18:47 UTC
