### ISSUE TITLE
Submit results and obtain image to share

### ISSUE THREAD

**Issue by nathan-osman** [sindresorhus/speed-test#25] opened 2015-11-07 06:47 UTC
After visiting the website and performing a speedtest, users are offered links to the results and a PNG image they can share containing the results of the test. It would be awesome if speed-test could provide this information, perhaps through a flag.

**Comment by sindresorhus** [comment] 2015-11-07 06:49
Duplicate of #18 and #12.

**Closed by sindresorhus** 2015-11-07 06:49 UTC
